// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpUG5azlvMmAnk_N2Yd6GZuvrSZv6T4Y',
    appId: '1:972179098886:web:cb9f18bbde623faa10e287',
    messagingSenderId: '972179098886',
    projectId: 'airbnbapp-f2e49',
    authDomain: 'airbnbapp-f2e49.firebaseapp.com',
    storageBucket: 'airbnbapp-f2e49.firebasestorage.app',
    measurementId: 'G-RELPWG15KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApc1W3viJXhr0Jh2AYP9PZkmRF1Pe58Jc',
    appId: '1:972179098886:android:0702a43e9456766810e287',
    messagingSenderId: '972179098886',
    projectId: 'airbnbapp-f2e49',
    storageBucket: 'airbnbapp-f2e49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIq5CBV3cmEPUjTBYb3I7rT0dVAu0nnWk',
    appId: '1:972179098886:ios:959c1faf15f9864c10e287',
    messagingSenderId: '972179098886',
    projectId: 'airbnbapp-f2e49',
    storageBucket: 'airbnbapp-f2e49.firebasestorage.app',
    iosClientId: '972179098886-fsim85k204t1k8lih6bk7fuar26mlcqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.airbnbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIq5CBV3cmEPUjTBYb3I7rT0dVAu0nnWk',
    appId: '1:972179098886:ios:959c1faf15f9864c10e287',
    messagingSenderId: '972179098886',
    projectId: 'airbnbapp-f2e49',
    storageBucket: 'airbnbapp-f2e49.firebasestorage.app',
    iosClientId: '972179098886-fsim85k204t1k8lih6bk7fuar26mlcqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.airbnbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKpUG5azlvMmAnk_N2Yd6GZuvrSZv6T4Y',
    appId: '1:972179098886:web:9994b88c4e06698210e287',
    messagingSenderId: '972179098886',
    projectId: 'airbnbapp-f2e49',
    authDomain: 'airbnbapp-f2e49.firebaseapp.com',
    storageBucket: 'airbnbapp-f2e49.firebasestorage.app',
    measurementId: 'G-4KR7NW3HLJ',
  );

}